service: contacts-api
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  key: '${file(./config/envVars.js):getEnvVars.key}'
  secret: '${file(./config/envVars.js):getEnvVars.secret}'
  region: '${file(./config/envVars.js):getEnvVars.region}'
functions:
  - '${file(src/handlers/contacts/contacts.serverless.yml)}'

plugins:
  - serverless-offline